#!/bin/bash
while [ "${*}" != "" ] ; do
    input="$1"
    makelossless -j "${input}" && makeaccess "${input}" && makeframes "${input}" && makemetadata "${input}" && checksumpackage "${input}"
    shift
done
